# Generated by Django 4.0.4 on 2022-08-13 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_snacks_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
